stages:
  - test
  - build
  - re_push

variables:
  BUILD_TAG: 'ci-$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA'
  CI_REGISTRY_FRONTEND_IMAGE: '$CI_REGISTRY_IMAGE/frontend'


test:
  image: python:3.7
  stage: test
  tags:
    - kube
  before_script:
    - pip install -r requirements.txt
    - pip install -e .
    - pip install pytest pytest-asyncio coverage
  script:
    - cd tests && coverage run -m pytest
    - coverage report
  coverage: '/TOTAL.+ ([0-9]{1,3}%)/'


build_tag_image:
  stage: build
  dependencies:
    - test
  tags:
    - shell
  only:
    - tags
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build -t auction-image .
    - docker run auction-image /app/run_tests.sh
    - docker tag auction-image $CI_REGISTRY_IMAGE:$TAG
    - docker push $CI_REGISTRY_FRONTEND_IMAGE:$TAG

push_latest:
  stage: re_push
  needs:
    - build_tag_image
  only:
    - /^[0-9]+\.[0-9]+\.[0-9]+$/
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker pull $CI_REGISTRY_IMAGE:$TAG
    - docker tag $CI_REGISTRY_IMAGE:$TAG $CI_REGISTRY_IMAGE:latest
    - docker push $CI_REGISTRY_FRONTEND_IMAGE:latest
