stages:
  - test
  - build
  - re_push

variables:
  CI_REGISTRY_FRONTEND_IMAGE: '$CI_REGISTRY_IMAGE/frontend'


test:
  image: python:3.7
  stage: test
  tags:
    - kube
  before_script:
    - pip install -r requirements.txt
    - pip install -e .
    - pip install pytest pytest-asyncio coverage
  script:
    - cd tests && coverage run -m pytest
    - coverage report
  coverage: '/TOTAL.+ ([0-9]{1,3}%)/'

.build_tag_image:
  stage: build
  dependencies:
    - test
  tags:
    - shell
  only:
    - tags
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build -t $REGISTRY_IMAGE:$CI_COMMIT_TAG $BUILD_CONTEXT
    - docker push $REGISTRY_IMAGE:$CI_COMMIT_TAG

.push_latest:
  stage: re_push
  only:
    - /^[0-9]+\.[0-9]+\.[0-9]+$/
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker pull $REGISTRY_IMAGE:$CI_COMMIT_TAG
    - docker tag $REGISTRY_IMAGE:$CI_COMMIT_TAG $REGISTRY_IMAGE:latest
    - docker push $REGISTRY_IMAGE:latest

build_backend_tag_image:
  extends: .build_tag_image
  variables:
    BUILD_CONTEXT: .
    REGISTRY_IMAGE: $CI_REGISTRY_IMAGE

push_backend_latest_image:
  extends: .push_latest
  needs:
    - build_backend_tag_image
  variables:
    REGISTRY_IMAGE: $CI_REGISTRY_IMAGE

build_frontend_tag_image:
  extends: .build_tag_image
  variables:
    BUILD_CONTEXT: ./frontend
    REGISTRY_IMAGE: $CI_REGISTRY_FRONTEND_IMAGE

push_frontend_latest_image:
  extends: .push_latest
  needs:
    - build_frontend_tag_image
  variables:
    REGISTRY_IMAGE: $CI_REGISTRY_FRONTEND_IMAGE