stages:
  - test
  - build

variables:
  BUILD_TAG: 'ci-$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA'
  CI_REGISTRY_FRONTEND_IMAGE: '$CI_REGISTRY_IMAGE/frontend'


test:
  image: python:3.7
  stage: test
  tags:
    - kube
  before_script:
    - pip install -r requirements.txt
    - pip install -e .
    - pip install pytest pytest-asyncio coverage
  script:
    - cd tests && coverage run -m pytest
    - coverage report
  coverage: '/TOTAL.+ ([0-9]{1,3}%)/'


.build:
  stage: build
  dependencies:
    - test
  tags:
    - shell
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE:$TAG .
    - docker push $CI_REGISTRY_IMAGE:$TAG
    - docker build -t $CI_REGISTRY_FRONTEND_IMAGE:$TAG .
    - docker push $CI_REGISTRY_FRONTEND_IMAGE:$TAG

build latest:
  extends: .build
  only:
    - /^[0-9]+\.[0-9]+\.[0-9]+$/
  variables:
    IMAGE: latest
    TAG: latest

build tags:
  extends: .build
  only:
    - tags
  variables:
    IMAGE: latest
    TAG: $CI_COMMIT_TAG