version: '3'

services:
  mongo:
    hostname: mongo
    image: 'bitnami/mongodb:latest'
    environment:
      MONGODB_ROOT_PASSWORD: example
      MONGODB_REPLICA_SET_MODE: primary
      MONGODB_REPLICA_SET_NAME: rs0
      MONGODB_REPLICA_SET_KEY: replicaSetKey
    logging:
      driver: "none"
    networks:
      - default

  mongo-express:
    image: mongo-express
    restart: always
    depends_on:
      - mongo
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_SERVER: mongo
    logging:
      driver: "none"
    networks:
      - default

  api:
    hostname: auctions-api
    build: .
    environment:
      - MONGODB_URL=mongodb://root:example@mongo:27017/?replicaSet=rs0
      - PYTHONUNBUFFERED=1
    volumes:
      - ./src:/app
      - ./tests:/app/tests
    ports:
      - 8000:8000
    depends_on:
      - mongo
    networks:
      - default

  databridge:
    build: .
    environment:
      - MONGODB_URL=mongodb://root:example@mongo:27017/?replicaSet=rs0
      - TEST_MODE=1
      - PYTHONUNBUFFERED=1
      - PUBLIC_API_HOST=http://api
      - API_HOST=http://api
      - API_TOKEN=auction
      - FEED_STEP_INTERVAL=5
      - API_LIMIT=50
    command: prozorro_auction.databridge.main
    volumes:
      - ./src:/app
    depends_on:
      - mongo
    networks:
      - default
      - openprocurementapi_default

  chronograph:
    build: .
    environment:
      - MONGODB_URL=mongodb://root:example@mongo:27017/?replicaSet=rs0
      - PYTHONUNBUFFERED=1
      - PUBLIC_API_HOST=http://api
      - API_HOST=http://api
      - API_TOKEN=auction
      - DS_HOST=http://ds.k8s.prozorro.gov.ua
      - DS_USER=test
      - DS_PASSWORD=test
    command: prozorro_auction.chronograph.main
    volumes:
      - ./src:/app
    ports:
      - 9092:9091
    depends_on:
      - mongo
    networks:
      - default
      - openprocurementapi_default

  monitor:
    build: .
    environment:
      - MONGODB_URL=mongodb://root:example@mongo:27017/?replicaSet=rs0
      - PYTHONUNBUFFERED=1
      - MONITOR_TIMER=0
      - MONITOR_PENDING_AUCTION=0
    command: prozorro_auction.monitor.main
    volumes:
      - ./src:/app
    ports:
      - 9091:9091
    depends_on:
      - mongo
    networks:
      - default

  frontend:
    image: docker-registry.prozorro.gov.ua/cdb/prozorro-auction-frontend:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api
    ports:
      - 8080:80
    networks:
      - default

networks:
    default: {}
    openprocurementapi_default:
        external: true
