import os


MONITOR_INTERVAL_SECONDS = int(os.environ.get("MONITOR_INTERVAL_SECONDS", 5))
MONITOR_TIMER_WARNING_LIMIT = int(os.environ.get("MONITOR_TIMER_WARNING_LIMIT", 2))
MONITOR_TIMER_ERROR_LIMIT = int(os.environ.get("MONITOR_TIMER_ERROR_LIMIT", 10))


MONITOR_TIMER = int(os.environ.get("MONITOR_TIMER", 1))
MONITOR_PENDING_AUCTION = int(os.environ.get("MONITOR_PENDING_AUCTION", 1))

MONITOR_EXPECTING_OFFSET_SECONDS = int(os.environ.get("MONITOR_EXPECTING_OFFSET_SECONDS", 60))
